### POST request to add a new gas station
POST http://localhost:3000/manager/gas-station
Accept: application/json
Content-Type: application/json

{
  "name": "Independent boterma bo gitar  Gas Station",
  "available": true,
  "yearOfCreation": 2023,
  "address": "456 Anot321654456645her St, City, Country",
  "location": "123.456, -789.123"
}
### GET request to retrieve gas stations
GET http://localhost:3000/manager/get/gas-station/675c6d77fece8243dd1712fc


### PUT request to update a gas station
PUT http://localhost:3000/manager/gas-station/675c6d77fece8243dd1712fc
Accept: application/json
Content-Type: application/json

{
  "name": "Updated Gas St boterma bo ka3lousa ation",
  "available": false,
  "yearOfCreation": 2022,
  "address": "789 Updated St, City, Country",
  "location": "321.654, -987.321"
}



### DELETE request to remove a gas station
DELETE http://localhost:3000/manager/gas-station/675c6c2efece8243dd1712fa

### GET request to remove a gas station
GET http://localhost:3000/manager/all/gas-stations
